.PHONY: benchmark

ITERATIONS ?= 3
DESTINATION ?= platform=iOS Simulator,name=iPhone 15 Pro Max,OS=26.0
SIMULATOR_ID ?=
IMPLEMENTATIONS ?=
SCROLL_UPS ?= 2
SCROLL_DOWNS ?= 1
CONFIGURATION ?= Debug

benchmark:
	LISTKIT_BENCHMARK_ITERATIONS="$(ITERATIONS)" \
	LISTKIT_BENCHMARK_DESTINATION="$(DESTINATION)" \
	LISTKIT_BENCHMARK_SIMULATOR_ID="$(SIMULATOR_ID)" \
	LISTKIT_BENCHMARK_IMPLEMENTATIONS="$(IMPLEMENTATIONS)" \
	LISTKIT_BENCHMARK_SCROLL_UPS="$(SCROLL_UPS)" \
	LISTKIT_BENCHMARK_SCROLL_DOWNS="$(SCROLL_DOWNS)" \
	LISTKIT_BENCHMARK_CONFIGURATION="$(CONFIGURATION)" \
	Benchmarks/scripts/run_ui_benchmark.sh
